Add service + allow control over what is autosaved
atom/autosave pull request #45
Opened 2015-08-13 04:40 UTC by akonwi

This is a step towards resolving #43. My Git-Plus package observes commit message files and if a save is triggered before the message is finished the commit happens anyway

2015-11-04 03:14 UTC, akonwi commented
Has anyone looked at this?

2016-01-11 21:28 UTC, jsg2021 commented
I'm looking forward to this.

2016-12-08 21:47 UTC, akonwi commented
@50Wliu Just following up. Does this have a chance at being accepted?

2016-12-08 22:24 UTC, 50Wliu commented
/cc @nathansobo for review

2016-12-13 16:26 UTC, nathansobo requested changes
Thanks! This looks like a cool addition. If you can address my requested changes I think we're close. Perhaps @50Wliu could help with the documentation description if you need input there.

2016-12-13 16:26 UTC, nathansobo commented on lib/autosave.coffee
> +  provideControls: -> dontSaveIf
What do you think about providing an object with a method so we can add other methods without breaking major version compatibility with the existing service?

2016-12-13 16:26 UTC, nathansobo commented on spec/controls-spec.coffee
> +describe 'Controls', ->
I'd also like to see a more integrated test of `autosave` itself that ensures it interacts with the service and doesn't save if a predicate returns true.

2016-12-13 16:26 UTC, nathansobo commented on README.md
> +### package.json
This example is great, but could you add some text in english describing this as well?

2016-12-13 16:26 UTC, nathansobo commented on README.md
> +consumeAutosave: (dontSaveIf) ->
Let's use ES6 for this example instead because we're trying to phase out CoffeeScript, though it's going to take a while.

2016-12-14 03:07 UTC, akonwi commented
Great! I'll make the changes

2016-12-14 05:45 UTC, akonwi commented
I removed the previously written tests for `Controls` and replaced them with an integrated test using a predicate. The description in the README may need more tweaking though

2016-12-14 18:38 UTC, nathansobo approved these changes

2016-12-14 18:55 UTC, nathansobo commented
@akonwi I made a few adjustments I'd like to push to your branch... can you [follow these instructions](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) to enable me to push to your fork for this branch?

2016-12-14 20:45 UTC, akonwi commented
@nathansobo Done

2016-12-15 18:47 UTC, akonwi commented
Cool! I just made a couple more changes for cleanup

2016-12-15 22:39 UTC, merged

2016-12-15 22:40 UTC, nathansobo commented
Great additions! Thanks for catching both of those things. Really appreciate you working with us on this one despite the extremely long delay in getting an initial review. Thanks for your efforts!